apiVersion: v1
kind: ConfigMap
metadata:
  name: nylon-legs-manhua-web-env
  labels:
    app.kubernetes.io/name: nylon-legs-manhua
    app.kubernetes.io/part-of: nylon-legs-manhua
data:
  NEXT_PUBLIC_WEB_URL: https://nylon-legs-manhua.lol
  NEXT_PUBLIC_PROJECT_NAME: nylon-legs-manhua
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: G-DR97CKPZ10
  NEXT_PUBLIC_CLARITY_PROJECT_ID: wazw1tamcn
  NEXT_PUBLIC_AUTH_DISABLED: "true"
  NEXT_PUBLIC_DEFAULT_THEME: dark
  NEXT_PUBLIC_LOCALE_DETECTION: "false"
