apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nylon-legs-manhua
  namespace: argocd
spec:
  description: Nylon Legs production website
  sourceRepos:
    - https://github.com/gateszhangc/nylon-legs-manhua.git
  destinations:
    - namespace: nylon-legs-manhua
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
